package candis.server.gui;

/**
 *
 * @author Enrico Joerns
 */
public class CheckCodeShowDialog extends javax.swing.JDialog {

	/**
	 * Creates new form CheckCodeShowDialog.
	 */
	public CheckCodeShowDialog(java.awt.Frame parent, boolean modal, String deviceID, String code) {
		super(parent, modal);
		setTitle(deviceID);
		initComponents();
		mCheckCodeField.setText(code);
		mHeadLabel.setText("Checkcode for " + deviceID);
		pack();
		setLocationRelativeTo(parent);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    mHeadLabel = new javax.swing.JLabel();
    mCheckCodeField = new javax.swing.JTextField();
    mCloseButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    mHeadLabel.setText("Check code");
    getContentPane().add(mHeadLabel, new java.awt.GridBagConstraints());

    mCheckCodeField.setColumns(6);
    mCheckCodeField.setEditable(false);
    mCheckCodeField.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
    mCheckCodeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    mCheckCodeField.setText("000000");
    mCheckCodeField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mCheckCodeFieldActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    getContentPane().add(mCheckCodeField, gridBagConstraints);

    mCloseButton.setText("Close");
    mCloseButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mCloseButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    getContentPane().add(mCloseButton, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void mCheckCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCheckCodeFieldActionPerformed
		// TODO add your handling code here:
  }//GEN-LAST:event_mCheckCodeFieldActionPerformed

  private void mCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCloseButtonActionPerformed
		// TODO add your handling code here:
  }//GEN-LAST:event_mCloseButtonActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField mCheckCodeField;
  private javax.swing.JButton mCloseButton;
  private javax.swing.JLabel mHeadLabel;
  // End of variables declaration//GEN-END:variables
}
