package candis.server.gui;

import candis.common.Settings;
import java.io.File;

/**
 *
 * @author Enrico Joerns
 */
public class OptionsDialog extends javax.swing.JDialog {

	/**
	 * Creates new form OptionsDialog.
	 */
	public OptionsDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(parent);
	}

	public void updateOptions() {
		mCheckCodeCB.getModel().setSelected(Settings.getBoolean("pincode_auth"));
		mAddConfirmCB.getModel().setSelected(Settings.getBoolean("manual_accept"));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    mCheckCodeCB = new javax.swing.JCheckBox();
    mAddConfirmCB = new javax.swing.JCheckBox();
    mSaveButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    mCheckCodeCB.setText("Client needs pin authorization");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    getContentPane().add(mCheckCodeCB, gridBagConstraints);

    mAddConfirmCB.setText("Server add client needs confirm");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    getContentPane().add(mAddConfirmCB, gridBagConstraints);

    mSaveButton.setText("Save");
    mSaveButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mSaveButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    getContentPane().add(mSaveButton, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void mSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSaveButtonActionPerformed
		Settings.setBoolean("pincode_auth", mCheckCodeCB.isSelected());
		Settings.setBoolean("manual_accept", mAddConfirmCB.isSelected());
		// TODO: worker thread?
		Settings.store(new File("settings.properties"));
		setVisible(false);
  }//GEN-LAST:event_mSaveButtonActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox mAddConfirmCB;
  private javax.swing.JCheckBox mCheckCodeCB;
  private javax.swing.JButton mSaveButton;
  // End of variables declaration//GEN-END:variables
}
