/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package candis.server.gui;

/**
 *
 * @author Enrico Joerns
 */
public class TaskPanel extends javax.swing.JPanel {

	private final String mID;
	
	public TaskPanel() {
		this("xxxxx");
	}

	/**
	 * Creates new form TaskPanel
	 */
	public TaskPanel(String id) {
		mID = id;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    mTaskIDLabel = new javax.swing.JLabel();
    mParametersLabel = new javax.swing.JLabel();
    mResultsLabel = new javax.swing.JLabel();
    mTaskIDValue = new javax.swing.JLabel();
    mParametersValue = new javax.swing.JLabel();
    mResultsValue = new javax.swing.JLabel();
    mRunningValue = new javax.swing.JLabel();

    setBorder(javax.swing.BorderFactory.createEtchedBorder());
    setLayout(new java.awt.GridBagLayout());

    jPanel1.setLayout(new java.awt.GridBagLayout());

    mTaskIDLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    mTaskIDLabel.setText("Task ID:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
    jPanel1.add(mTaskIDLabel, gridBagConstraints);

    mParametersLabel.setText("Parameters:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    jPanel1.add(mParametersLabel, gridBagConstraints);

    mResultsLabel.setText("Results:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    jPanel1.add(mResultsLabel, gridBagConstraints);

    mTaskIDValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    mTaskIDValue.setText("00000");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    gridBagConstraints.weightx = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
    jPanel1.add(mTaskIDValue, gridBagConstraints);

    mParametersValue.setText("0");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
    jPanel1.add(mParametersValue, gridBagConstraints);

    mResultsValue.setText("0");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
    jPanel1.add(mResultsValue, gridBagConstraints);

    mRunningValue.setText("stopped");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    gridBagConstraints.weightx = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
    jPanel1.add(mRunningValue, gridBagConstraints);

    mTaskIDValue.setText(mID);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.weightx = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(jPanel1, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel mParametersLabel;
  private javax.swing.JLabel mParametersValue;
  private javax.swing.JLabel mResultsLabel;
  private javax.swing.JLabel mResultsValue;
  private javax.swing.JLabel mRunningValue;
  private javax.swing.JLabel mTaskIDLabel;
  private javax.swing.JLabel mTaskIDValue;
  // End of variables declaration//GEN-END:variables
}
